name: my_tasks
description: A personal task management application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Splash screen
  assets:
    - assets/lottie/task.json

  # Custom app icon (you can add your own icon file)
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/icon.png"
