name: my_tasks
description: A personal task management application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3

  lottie: ^2.7.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1

  # Firebase
  firebase_auth: ^4.5.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.17.5

  # State Management
  provider: ^6.0.5

  # Local Storage
  shared_preferences: ^2.5.3

  # UI
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  image_picker: ^1.1.2
  firebase_storage: ^11.6.5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Splash screen
  assets:
    - assets/lottie/task.json

  # Custom app icon (you can add your own icon file)
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/icon.png"
