// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8cg_qlQ6S5brK9KfXFt9YXBWxRxFu2k',
    appId: '1:333365618054:web:d5ec9b7051964156883807',
    messagingSenderId: '333365618054',
    projectId: 'taskmanager-f98ff',
    authDomain: 'taskmanager-f98ff.firebaseapp.com',
    storageBucket: 'taskmanager-f98ff.firebasestorage.app',
    measurementId: 'G-MB19R7405S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNHxtNk_7lugYO1YsBdT-w5WG8jRnAX4',
    appId: '1:333365618054:android:1a0ae8c486b91775883807',
    messagingSenderId: '333365618054',
    projectId: 'taskmanager-f98ff',
    storageBucket: 'taskmanager-f98ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnynkj3-5eza-1Dc4K4eZuJi-iKHbBfw',
    appId: '1:333365618054:ios:47376cfa44b1203e883807',
    messagingSenderId: '333365618054',
    projectId: 'taskmanager-f98ff',
    storageBucket: 'taskmanager-f98ff.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKnynkj3-5eza-1Dc4K4eZuJi-iKHbBfw',
    appId: '1:333365618054:ios:47376cfa44b1203e883807',
    messagingSenderId: '333365618054',
    projectId: 'taskmanager-f98ff',
    storageBucket: 'taskmanager-f98ff.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8cg_qlQ6S5brK9KfXFt9YXBWxRxFu2k',
    appId: '1:333365618054:web:e5887ab40597c839883807',
    messagingSenderId: '333365618054',
    projectId: 'taskmanager-f98ff',
    authDomain: 'taskmanager-f98ff.firebaseapp.com',
    storageBucket: 'taskmanager-f98ff.firebasestorage.app',
    measurementId: 'G-2HZY3S15S6',
  );
}
