name: study_hub
description: A study app with quiz, tasks, chat, and profile using Firebase Realtime Database.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: any
  provider: any
  shared_preferences: any
  intl: any
  uuid: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  firebase_database: any
  firebase_storage: any

  # Ads
  google_mobile_ads: any

  # UI helpers
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quiz/questions.json